/**
 * Brazilian Cities and Neighborhoods Data
 *
 * Comprehensive list of Brazilian cities with their major neighborhoods for product filtering and selection.
 * Covers major cities by population, tourist destinations, and metropolitan areas.
 */

/**
 * Neighborhood interface
 */
export interface Neighborhood {
  /** Neighborhood slug/ID used for filtering */
  value: string
  /** Display label in Portuguese */
  label: string
}

/**
 * City interface for Brazilian cities
 */
export interface City {
  /** City slug/ID used for filtering */
  value: string
  /** Display label in Portuguese */
  label: string
  /** State abbreviation */
  state: string
  /** Population (approximate, for sorting) */
  population: number
  /** Major neighborhoods in this city */
  neighborhoods: Neighborhood[]
}

/**
 * Brazilian cities with neighborhoods
 * Ordered by population/market size
 */
export const BRAZILIAN_CITIES: readonly City[] = [
  // ============================================================================
  // TOP 10 - Major Metropolises
  // ============================================================================
  {
    value: 'sao-paulo',
    label: 'São Paulo',
    state: 'SP',
    population: 11_900_000,
    neighborhoods: [
      { value: 'pinheiros', label: 'Pinheiros' },
      { value: 'jardins', label: 'Jardins' },
      { value: 'vila-madalena', label: 'Vila Madalena' },
      { value: 'moema', label: 'Moema' },
      { value: 'itaim-bibi', label: 'Itaim Bibi' },
      { value: 'perdizes', label: 'Perdizes' },
      { value: 'consolacao', label: 'Consolação' },
      { value: 'bela-vista', label: 'Bela Vista' },
      { value: 'liberdade', label: 'Liberdade' },
      { value: 'santana', label: 'Santana' },
      { value: 'tatuape', label: 'Tatuapé' },
      { value: 'mooca', label: 'Mooca' },
      { value: 'vila-mariana', label: 'Vila Mariana' },
      { value: 'brooklin', label: 'Brooklin' },
      { value: 'campo-belo', label: 'Campo Belo' },
      { value: 'higienopolis', label: 'Higienópolis' },
      { value: 'pompeia', label: 'Pompeia' },
      { value: 'lapa', label: 'Lapa' },
      { value: 'barra-funda', label: 'Barra Funda' },
      { value: 'bras', label: 'Brás' },
      { value: 'pari', label: 'Pari' },
      { value: 'belem-sp', label: 'Belém' },
      { value: 'penha', label: 'Penha' },
      { value: 'vila-prudente', label: 'Vila Prudente' },
      { value: 'ipiranga', label: 'Ipiranga' },
      { value: 'saude', label: 'Saúde' },
      { value: 'jabaquara', label: 'Jabaquara' },
      { value: 'santo-amaro', label: 'Santo Amaro' },
      { value: 'campo-limpo', label: 'Campo Limpo' },
      { value: 'capao-redondo', label: 'Capão Redondo' },
      { value: 'vila-andrade', label: 'Vila Andrade' },
      { value: 'morumbi', label: 'Morumbi' },
      { value: 'butanta', label: 'Butantã' },
      { value: 'vila-sonia', label: 'Vila Sônia' },
      { value: 'raposo-tavares', label: 'Raposo Tavares' },
      { value: 'pirituba', label: 'Pirituba' },
      { value: 'freguesia-do-o', label: 'Freguesia do Ó' },
      { value: 'casa-verde', label: 'Casa Verde' },
      { value: 'tucuruvi', label: 'Tucuruvi' },
      { value: 'mandaqui', label: 'Mandaqui' },
      { value: 'jardim-paulista', label: 'Jardim Paulista' },
      { value: 'paraiso', label: 'Paraíso' },
      { value: 'aclimacao', label: 'Aclimação' },
      { value: 'cambuci', label: 'Cambuci' },
      { value: 'centro-sp', label: 'Centro' },
      { value: 'republica', label: 'República' },
      { value: 'se', label: 'Sé' },
      { value: 'santa-cecilia', label: 'Santa Cecília' },
    ],
  },
  {
    value: 'rio-de-janeiro',
    label: 'Rio de Janeiro',
    state: 'RJ',
    population: 6_750_000,
    neighborhoods: [
      // Zona Sul
      { value: 'copacabana', label: 'Copacabana' },
      { value: 'ipanema', label: 'Ipanema' },
      { value: 'leblon', label: 'Leblon' },
      { value: 'botafogo', label: 'Botafogo' },
      { value: 'flamengo', label: 'Flamengo' },
      { value: 'laranjeiras', label: 'Laranjeiras' },
      { value: 'catete', label: 'Catete' },
      { value: 'gloria', label: 'Glória' },
      { value: 'urca', label: 'Urca' },
      { value: 'leme', label: 'Leme' },
      { value: 'humaita', label: 'Humaitá' },
      { value: 'cosme-velho', label: 'Cosme Velho' },
      { value: 'gavea', label: 'Gávea' },
      { value: 'jardim-botanico', label: 'Jardim Botânico' },
      { value: 'lagoa', label: 'Lagoa' },
      { value: 'sao-conrado', label: 'São Conrado' },
      { value: 'vidigal', label: 'Vidigal' },
      // Zona Oeste
      { value: 'barra-da-tijuca', label: 'Barra da Tijuca' },
      { value: 'recreio', label: 'Recreio dos Bandeirantes' },
      { value: 'jacarepagua', label: 'Jacarepaguá' },
      { value: 'taquara', label: 'Taquara' },
      { value: 'freguesia-rj', label: 'Freguesia' },
      { value: 'pechincha', label: 'Pechincha' },
      { value: 'tanque', label: 'Tanque' },
      { value: 'anil', label: 'Anil' },
      { value: 'gardenia-azul', label: 'Gardênia Azul' },
      { value: 'curicica', label: 'Curicica' },
      { value: 'campo-grande-rj', label: 'Campo Grande' },
      { value: 'bangu', label: 'Bangu' },
      { value: 'realengo', label: 'Realengo' },
      { value: 'padre-miguel', label: 'Padre Miguel' },
      { value: 'santissimo', label: 'Santíssimo' },
      // Zona Norte
      { value: 'tijuca', label: 'Tijuca' },
      { value: 'meier', label: 'Méier' },
      { value: 'vila-isabel', label: 'Vila Isabel' },
      { value: 'maracana', label: 'Maracanã' },
      { value: 'andarai', label: 'Andaraí' },
      { value: 'grajau', label: 'Grajaú' },
      { value: 'engenho-novo', label: 'Engenho Novo' },
      { value: 'cachambi', label: 'Cachambi' },
      { value: 'bonsucesso', label: 'Bonsucesso' },
      { value: 'penha-rj', label: 'Penha' },
      { value: 'olaria', label: 'Olaria' },
      { value: 'ramos', label: 'Ramos' },
      { value: 'ilha-do-governador', label: 'Ilha do Governador' },
      // Centro
      { value: 'lapa-rj', label: 'Lapa' },
      { value: 'centro-rj', label: 'Centro' },
      { value: 'santa-teresa', label: 'Santa Teresa' },
      { value: 'saude-rj', label: 'Saúde' },
      { value: 'gamboa', label: 'Gamboa' },
      { value: 'santo-cristo', label: 'Santo Cristo' },
      { value: 'cidade-nova', label: 'Cidade Nova' },
      { value: 'sao-cristovao', label: 'São Cristóvão' },
    ],
  },
  {
    value: 'brasilia',
    label: 'Brasília',
    state: 'DF',
    population: 3_000_000,
    neighborhoods: [
      { value: 'asa-sul', label: 'Asa Sul' },
      { value: 'asa-norte', label: 'Asa Norte' },
      { value: 'lago-sul', label: 'Lago Sul' },
      { value: 'lago-norte', label: 'Lago Norte' },
      { value: 'sudoeste', label: 'Sudoeste' },
      { value: 'noroeste', label: 'Noroeste' },
      { value: 'taguatinga', label: 'Taguatinga' },
      { value: 'aguas-claras', label: 'Águas Claras' },
      { value: 'guara', label: 'Guará' },
      { value: 'samambaia', label: 'Samambaia' },
      { value: 'ceilandia', label: 'Ceilândia' },
      { value: 'park-way', label: 'Park Way' },
      { value: 'cruzeiro', label: 'Cruzeiro' },
      { value: 'octogonal', label: 'Octogonal' },
      { value: 'vicente-pires', label: 'Vicente Pires' },
      { value: 'sobradinho', label: 'Sobradinho' },
      { value: 'planaltina', label: 'Planaltina' },
      { value: 'gama', label: 'Gama' },
      { value: 'santa-maria-df', label: 'Santa Maria' },
      { value: 'recanto-das-emas', label: 'Recanto das Emas' },
      { value: 'riacho-fundo', label: 'Riacho Fundo' },
      { value: 'jardim-botanico-df', label: 'Jardim Botânico' },
      { value: 'sao-sebastiao', label: 'São Sebastião' },
      { value: 'paranoa', label: 'Paranoá' },
    ],
  },
  {
    value: 'fortaleza',
    label: 'Fortaleza',
    state: 'CE',
    population: 2_700_000,
    neighborhoods: [
      { value: 'meireles', label: 'Meireles' },
      { value: 'aldeota', label: 'Aldeota' },
      { value: 'praia-de-iracema', label: 'Praia de Iracema' },
      { value: 'mucuripe', label: 'Mucuripe' },
      { value: 'papicu', label: 'Papicu' },
      { value: 'varjota', label: 'Varjota' },
      { value: 'dionisio-torres', label: 'Dionísio Torres' },
      { value: 'fatima', label: 'Fátima' },
      { value: 'benfica', label: 'Benfica' },
      { value: 'centro-fortaleza', label: 'Centro' },
      { value: 'coco', label: 'Cocó' },
      { value: 'agua-fria-ce', label: 'Água Fria' },
      { value: 'edson-queiroz', label: 'Edson Queiroz' },
      { value: 'messejana', label: 'Messejana' },
      { value: 'parangaba', label: 'Parangaba' },
      { value: 'montese', label: 'Montese' },
      { value: 'rodolfo-teofilo', label: 'Rodolfo Teófilo' },
      { value: 'parquelândia', label: 'Parquelândia' },
      { value: 'cidade-2000', label: 'Cidade 2000' },
      { value: 'guararapes', label: 'Guararapes' },
      { value: 'luciano-cavalcante', label: 'Luciano Cavalcante' },
      { value: 'cambeba', label: 'Cambeba' },
      { value: 'jose-bonifacio-ce', label: 'José Bonifácio' },
      { value: 'joaquim-tavora', label: 'Joaquim Távora' },
      { value: 'barra-do-ceara', label: 'Barra do Ceará' },
      { value: 'carlito-pamplona', label: 'Carlito Pamplona' },
      { value: 'monte-castelo-ce', label: 'Monte Castelo' },
      { value: 'jacarecanga', label: 'Jacarecanga' },
    ],
  },
  {
    value: 'salvador',
    label: 'Salvador',
    state: 'BA',
    population: 2_600_000,
    neighborhoods: [
      { value: 'barra', label: 'Barra' },
      { value: 'ondina', label: 'Ondina' },
      { value: 'rio-vermelho', label: 'Rio Vermelho' },
      { value: 'pelourinho', label: 'Pelourinho' },
      { value: 'pituba', label: 'Pituba' },
      { value: 'itaigara', label: 'Itaigara' },
      { value: 'caminho-das-arvores', label: 'Caminho das Árvores' },
      { value: 'stella-maris', label: 'Stella Maris' },
      { value: 'itapua', label: 'Itapuã' },
      { value: 'graca', label: 'Graça' },
      { value: 'vitoria-ba', label: 'Vitória' },
      { value: 'canela', label: 'Canela' },
      { value: 'paralela', label: 'Paralela' },
      { value: 'horto-florestal', label: 'Horto Florestal' },
      { value: 'costa-azul', label: 'Costa Azul' },
      { value: 'amaralina', label: 'Amaralina' },
      { value: 'nordeste-amaralina', label: 'Nordeste de Amaralina' },
      { value: 'imbui', label: 'Imbuí' },
      { value: 'boca-do-rio', label: 'Boca do Rio' },
      { value: 'patamares', label: 'Patamares' },
      { value: 'piatã', label: 'Piatã' },
      { value: 'stiep', label: 'Stiep' },
      { value: 'garcia', label: 'Garcia' },
      { value: 'federacao', label: 'Federação' },
      { value: 'brotas', label: 'Brotas' },
      { value: 'nazare-ba', label: 'Nazaré' },
      { value: 'barris', label: 'Barris' },
      { value: 'bonfim', label: 'Bonfim' },
      { value: 'liberdade-ba', label: 'Liberdade' },
      { value: 'comercio', label: 'Comércio' },
      { value: 'centro-historico-ba', label: 'Centro Histórico' },
    ],
  },
  {
    value: 'belo-horizonte',
    label: 'Belo Horizonte',
    state: 'MG',
    population: 2_500_000,
    neighborhoods: [
      { value: 'savassi', label: 'Savassi' },
      { value: 'funcionarios', label: 'Funcionários' },
      { value: 'lourdes', label: 'Lourdes' },
      { value: 'santo-agostinho', label: 'Santo Agostinho' },
      { value: 'serra', label: 'Serra' },
      { value: 'buritis', label: 'Buritis' },
      { value: 'pampulha', label: 'Pampulha' },
      { value: 'centro-bh', label: 'Centro' },
      { value: 'santa-efigenia', label: 'Santa Efigênia' },
      { value: 'anchieta', label: 'Anchieta' },
      { value: 'sion', label: 'Sion' },
      { value: 'belvedere', label: 'Belvedere' },
      { value: 'gutierrez', label: 'Gutierrez' },
      { value: 'mangabeiras', label: 'Mangabeiras' },
      { value: 'cidade-jardim-bh', label: 'Cidade Jardim' },
      { value: 'santa-lucia-bh', label: 'Santa Lúcia' },
      { value: 'luxemburgo', label: 'Luxemburgo' },
      { value: 'carlos-prates', label: 'Carlos Prates' },
      { value: 'padre-eustaquio', label: 'Padre Eustáquio' },
      { value: 'caicaras', label: 'Caiçaras' },
      { value: 'prado', label: 'Prado' },
      { value: 'calafate', label: 'Calafate' },
      { value: 'barroca', label: 'Barroca' },
      { value: 'floresta-bh', label: 'Floresta' },
      { value: 'santa-tereza-bh', label: 'Santa Tereza' },
      { value: 'sagrada-familia', label: 'Sagrada Família' },
      { value: 'santo-antonio-bh', label: 'Santo Antônio' },
      { value: 'carmo', label: 'Carmo' },
      { value: 'cruzeiro-bh', label: 'Cruzeiro' },
      { value: 'ouro-preto-bh', label: 'Ouro Preto' },
      { value: 'castelo-bh', label: 'Castelo' },
      { value: 'jaragua-bh', label: 'Jaraguá' },
    ],
  },
  {
    value: 'manaus',
    label: 'Manaus',
    state: 'AM',
    population: 2_250_000,
    neighborhoods: [
      { value: 'centro-manaus', label: 'Centro' },
      { value: 'adrianopolis', label: 'Adrianópolis' },
      { value: 'nossa-senhora-gracas', label: 'Nossa Senhora das Graças' },
      { value: 'chapada', label: 'Chapada' },
      { value: 'parque-10', label: 'Parque 10 de Novembro' },
      { value: 'flores', label: 'Flores' },
      { value: 'vieiralves', label: 'Vieiralves' },
      { value: 'aleixo', label: 'Aleixo' },
      { value: 'dom-pedro', label: 'Dom Pedro' },
      { value: 'ponta-negra-manaus', label: 'Ponta Negra' },
      { value: 'cidade-nova-manaus', label: 'Cidade Nova' },
      { value: 'compensa', label: 'Compensa' },
      { value: 'sao-jorge-manaus', label: 'São Jorge' },
      { value: 'santo-antonio-manaus', label: 'Santo Antônio' },
      { value: 'praça-14', label: 'Praça 14 de Janeiro' },
      { value: 'cachoeirinha-manaus', label: 'Cachoeirinha' },
      { value: 'japiim', label: 'Japiim' },
      { value: 'petrópolis-manaus', label: 'Petrópolis' },
      { value: 'coroado', label: 'Coroado' },
      { value: 'taruma', label: 'Tarumã' },
    ],
  },
  {
    value: 'curitiba',
    label: 'Curitiba',
    state: 'PR',
    population: 1_950_000,
    neighborhoods: [
      { value: 'batel', label: 'Batel' },
      { value: 'agua-verde', label: 'Água Verde' },
      { value: 'centro-curitiba', label: 'Centro' },
      { value: 'bigorrilho', label: 'Bigorrilho' },
      { value: 'champagnat', label: 'Champagnat' },
      { value: 'juveve', label: 'Juvevê' },
      { value: 'cabral', label: 'Cabral' },
      { value: 'alto-da-xv', label: 'Alto da XV' },
      { value: 'santa-felicidade', label: 'Santa Felicidade' },
      { value: 'portao', label: 'Portão' },
      { value: 'reboucas', label: 'Rebouças' },
      { value: 'ecoville', label: 'Ecoville' },
      { value: 'merces', label: 'Mercês' },
      { value: 'ahu', label: 'Ahú' },
      { value: 'alto-da-gloria', label: 'Alto da Glória' },
      { value: 'jardim-social', label: 'Jardim Social' },
      { value: 'jardim-botanico-ctb', label: 'Jardim Botânico' },
      { value: 'bom-retiro-ctb', label: 'Bom Retiro' },
      { value: 'centro-civico', label: 'Centro Cívico' },
      { value: 'sao-francisco-ctb', label: 'São Francisco' },
      { value: 'cristo-rei', label: 'Cristo Rei' },
      { value: 'bacacheri', label: 'Bacacheri' },
      { value: 'boa-vista-ctb', label: 'Boa Vista' },
      { value: 'pilarzinho', label: 'Pilarzinho' },
      { value: 'tingui', label: 'Tingui' },
      { value: 'santa-quiteria', label: 'Santa Quitéria' },
      { value: 'campina-siqueira', label: 'Campina do Siqueira' },
      { value: 'seminario', label: 'Seminário' },
      { value: 'vila-izabel', label: 'Vila Izabel' },
      { value: 'novo-mundo', label: 'Novo Mundo' },
      { value: 'prado-velho', label: 'Prado Velho' },
      { value: 'guaira', label: 'Guaíra' },
      { value: 'lindoia-ctb', label: 'Lindóia' },
      { value: 'fanny', label: 'Fanny' },
      { value: 'hauer', label: 'Hauer' },
      { value: 'xaxim', label: 'Xaxim' },
    ],
  },
  {
    value: 'recife',
    label: 'Recife',
    state: 'PE',
    population: 1_650_000,
    neighborhoods: [
      { value: 'boa-viagem', label: 'Boa Viagem' },
      { value: 'piedade', label: 'Piedade' },
      { value: 'centro-recife', label: 'Centro' },
      { value: 'recife-antigo', label: 'Recife Antigo' },
      { value: 'casa-forte', label: 'Casa Forte' },
      { value: 'espinheiro', label: 'Espinheiro' },
      { value: 'gracas-recife', label: 'Graças' },
      { value: 'derby', label: 'Derby' },
      { value: 'aflitos', label: 'Aflitos' },
      { value: 'madalena', label: 'Madalena' },
      { value: 'torre', label: 'Torre' },
      { value: 'pina', label: 'Pina' },
      { value: 'setubal', label: 'Setúbal' },
      { value: 'parnamirim-recife', label: 'Parnamirim' },
      { value: 'tamarineira', label: 'Tamarineira' },
      { value: 'jaqueira', label: 'Jaqueira' },
      { value: 'apipucos', label: 'Apipucos' },
      { value: 'casa-amarela', label: 'Casa Amarela' },
      { value: 'poco-panela', label: 'Poço da Panela' },
      { value: 'santana-recife', label: 'Santana' },
      { value: 'encruzilhada', label: 'Encruzilhada' },
      { value: 'rosarinho', label: 'Rosarinho' },
      { value: 'torreao', label: 'Torreão' },
      { value: 'boa-vista-recife', label: 'Boa Vista' },
      { value: 'santo-amaro-recife', label: 'Santo Amaro' },
      { value: 'santo-antonio-recife', label: 'Santo Antônio' },
      { value: 'sao-jose-recife', label: 'São José' },
      { value: 'imbiribeira', label: 'Imbiribeira' },
      { value: 'ibura', label: 'Ibura' },
      { value: 'jardim-sao-paulo', label: 'Jardim São Paulo' },
    ],
  },
  {
    value: 'goiania',
    label: 'Goiânia',
    state: 'GO',
    population: 1_550_000,
    neighborhoods: [
      { value: 'setor-bueno', label: 'Setor Bueno' },
      { value: 'setor-marista', label: 'Setor Marista' },
      { value: 'setor-oeste', label: 'Setor Oeste' },
      { value: 'jardim-goias', label: 'Jardim Goiás' },
      { value: 'setor-central', label: 'Setor Central' },
      { value: 'setor-sul', label: 'Setor Sul' },
      { value: 'setor-universitario', label: 'Setor Universitário' },
      { value: 'alphaville-goiania', label: 'Alphaville' },
      { value: 'vila-nova', label: 'Vila Nova' },
      { value: 'jardim-america', label: 'Jardim América' },
      { value: 'setor-aeroporto', label: 'Setor Aeroporto' },
      { value: 'setor-campinas', label: 'Setor Campinas' },
      { value: 'setor-coimbra', label: 'Setor Coimbra' },
      { value: 'setor-nova-suica', label: 'Nova Suíça' },
      { value: 'setor-bela-vista', label: 'Setor Bela Vista' },
      { value: 'setor-pedro-ludovico', label: 'Setor Pedro Ludovico' },
      { value: 'setor-alto-imbui', label: 'Alto da Glória' },
      { value: 'parque-amazonia', label: 'Parque Amazônia' },
      { value: 'parque-flamboyant', label: 'Parque Flamboyant' },
      { value: 'setor-norte-ferroviario', label: 'Setor Norte Ferroviário' },
      { value: 'jardim-europa', label: 'Jardim Europa' },
      { value: 'vila-redenção', label: 'Vila Redenção' },
      { value: 'setor-leste-universitario', label: 'Setor Leste Universitário' },
    ],
  },
  // ============================================================================
  // TOP 11-20 - Major Regional Capitals
  // ============================================================================
  {
    value: 'porto-alegre',
    label: 'Porto Alegre',
    state: 'RS',
    population: 1_490_000,
    neighborhoods: [
      { value: 'moinhos-de-vento', label: 'Moinhos de Vento' },
      { value: 'bela-vista-poa', label: 'Bela Vista' },
      { value: 'cidade-baixa', label: 'Cidade Baixa' },
      { value: 'centro-historico-poa', label: 'Centro Histórico' },
      { value: 'menino-deus', label: 'Menino Deus' },
      { value: 'petropolis', label: 'Petrópolis' },
      { value: 'auxiliadora', label: 'Auxiliadora' },
      { value: 'mont-serrat', label: 'Mont\'Serrat' },
      { value: 'rio-branco-poa', label: 'Rio Branco' },
      { value: 'independencia', label: 'Independência' },
      { value: 'floresta-poa', label: 'Floresta' },
      { value: 'santana-poa', label: 'Santana' },
      { value: 'tristeza', label: 'Tristeza' },
      { value: 'ipanema-poa', label: 'Ipanema' },
      { value: 'cavalhada', label: 'Cavalhada' },
      { value: 'cristal', label: 'Cristal' },
      { value: 'teresopolis-poa', label: 'Teresópolis' },
      { value: 'gloria-poa', label: 'Glória' },
      { value: 'medianeira', label: 'Medianeira' },
      { value: 'partenon', label: 'Partenon' },
      { value: 'jardim-botanico-poa', label: 'Jardim Botânico' },
      { value: 'bom-fim', label: 'Bom Fim' },
      { value: 'farroupilha', label: 'Farroupilha' },
      { value: 'boa-vista-poa', label: 'Boa Vista' },
      { value: 'higienopolis-poa', label: 'Higienópolis' },
      { value: 'passo-areia', label: 'Passo d\'Areia' },
      { value: 'sao-joao-poa', label: 'São João' },
      { value: 'navegantes-poa', label: 'Navegantes' },
      { value: 'jardim-itu', label: 'Jardim Itú' },
      { value: 'vila-ipiranga', label: 'Vila Ipiranga' },
    ],
  },
  {
    value: 'belem',
    label: 'Belém',
    state: 'PA',
    population: 1_500_000,
    neighborhoods: [
      { value: 'nazare', label: 'Nazaré' },
      { value: 'umarizal', label: 'Umarizal' },
      { value: 'batista-campos', label: 'Batista Campos' },
      { value: 'cidade-velha', label: 'Cidade Velha' },
      { value: 'campina', label: 'Campina' },
      { value: 'reduto', label: 'Reduto' },
      { value: 'marco', label: 'Marco' },
      { value: 'pedreira', label: 'Pedreira' },
      { value: 'sao-bras', label: 'São Brás' },
      { value: 'telegrafo', label: 'Telégrafo' },
      { value: 'cremacao', label: 'Cremação' },
      { value: 'jurunas', label: 'Jurunas' },
      { value: 'guama', label: 'Guamá' },
      { value: 'canudos', label: 'Canudos' },
      { value: 'terra-firme', label: 'Terra Firme' },
      { value: 'sacramenta', label: 'Sacramenta' },
      { value: 'marambaia', label: 'Marambaia' },
      { value: 'mangueirão', label: 'Mangueirão' },
      { value: 'parque-verde', label: 'Parque Verde' },
      { value: 'castanheira', label: 'Castanheira' },
    ],
  },
  {
    value: 'guarulhos',
    label: 'Guarulhos',
    state: 'SP',
    population: 1_400_000,
    neighborhoods: [
      { value: 'centro-guarulhos', label: 'Centro' },
      { value: 'vila-galvao', label: 'Vila Galvão' },
      { value: 'gopouva', label: 'Gopouva' },
      { value: 'macedo', label: 'Macedo' },
      { value: 'vila-rosalia', label: 'Vila Rosália' },
      { value: 'vila-augusta', label: 'Vila Augusta' },
      { value: 'picanco', label: 'Picanço' },
      { value: 'jardim-maia', label: 'Jardim Maia' },
      { value: 'taboao', label: 'Taboão' },
      { value: 'aeroporto-guarulhos', label: 'Aeroporto' },
      { value: 'bosque-maia', label: 'Bosque Maia' },
      { value: 'jardim-city', label: 'Jardim City' },
      { value: 'ponte-grande', label: 'Ponte Grande' },
      { value: 'vila-barros', label: 'Vila Barros' },
      { value: 'bonsucesso-gru', label: 'Bonsucesso' },
      { value: 'jardim-presidente-dutra', label: 'Jardim Presidente Dutra' },
      { value: 'jardim-sao-joao', label: 'Jardim São João' },
      { value: 'cumbica', label: 'Cumbica' },
      { value: 'pimentas', label: 'Pimentas' },
      { value: 'cocaia', label: 'Cocaia' },
    ],
  },
  {
    value: 'campinas',
    label: 'Campinas',
    state: 'SP',
    population: 1_220_000,
    neighborhoods: [
      { value: 'cambui', label: 'Cambuí' },
      { value: 'centro-campinas', label: 'Centro' },
      { value: 'taquaral', label: 'Taquaral' },
      { value: 'barao-geraldo', label: 'Barão Geraldo' },
      { value: 'nova-campinas', label: 'Nova Campinas' },
      { value: 'guanabara', label: 'Guanabara' },
      { value: 'jardim-chapadao', label: 'Jardim Chapadão' },
      { value: 'bosque', label: 'Bosque' },
      { value: 'jardim-paulista-campinas', label: 'Jardim Paulista' },
      { value: 'alphaville-campinas', label: 'Alphaville' },
      { value: 'sousas', label: 'Sousas' },
      { value: 'joaquim-egidio', label: 'Joaquim Egídio' },
      { value: 'castelo', label: 'Castelo' },
      { value: 'mansoes-santo-antonio', label: 'Mansões Santo Antônio' },
      { value: 'parque-prado', label: 'Parque Prado' },
      { value: 'botafogo-campinas', label: 'Botafogo' },
      { value: 'vila-industrial-campinas', label: 'Vila Industrial' },
      { value: 'swift', label: 'Swift' },
      { value: 'parque-italia', label: 'Parque Itália' },
      { value: 'jardim-flamboyant', label: 'Jardim Flamboyant' },
      { value: 'parque-das-universidades', label: 'Parque das Universidades' },
    ],
  },
  {
    value: 'sao-luis',
    label: 'São Luís',
    state: 'MA',
    population: 1_115_000,
    neighborhoods: [
      { value: 'centro-historico-slz', label: 'Centro Histórico' },
      { value: 'renascenca', label: 'Renascença' },
      { value: 'calhau', label: 'Calhau' },
      { value: 'ponta-dareia', label: 'Ponta d\'Areia' },
      { value: 'sao-francisco', label: 'São Francisco' },
      { value: 'olho-dagua', label: 'Olho d\'Água' },
      { value: 'cohama', label: 'Cohama' },
      { value: 'turu', label: 'Turu' },
      { value: 'peninsula', label: 'Península' },
      { value: 'jardim-eldorado', label: 'Jardim Eldorado' },
      { value: 'cohafuma', label: 'Cohafuma' },
      { value: 'vinhais', label: 'Vinhais' },
      { value: 'angelim', label: 'Angelim' },
      { value: 'anil', label: 'Anil' },
      { value: 'ipase', label: 'Ipase' },
      { value: 'planalto-aurora', label: 'Planalto Aurora' },
      { value: 'sao-cristovao-slz', label: 'São Cristóvão' },
      { value: 'jordoa', label: 'Jordoá' },
    ],
  },
  {
    value: 'maceio',
    label: 'Maceió',
    state: 'AL',
    population: 1_030_000,
    neighborhoods: [
      { value: 'ponta-verde', label: 'Ponta Verde' },
      { value: 'pajucara', label: 'Pajuçara' },
      { value: 'jatiuca', label: 'Jatiúca' },
      { value: 'cruz-das-almas', label: 'Cruz das Almas' },
      { value: 'farol', label: 'Farol' },
      { value: 'prado-maceio', label: 'Prado' },
      { value: 'mangabeiras-maceio', label: 'Mangabeiras' },
      { value: 'gruta-de-lourdes', label: 'Gruta de Lourdes' },
      { value: 'jaragua-maceio', label: 'Jaraguá' },
      { value: 'centro-maceio', label: 'Centro' },
      { value: 'stella-maris-maceio', label: 'Stella Maris' },
      { value: 'riacho-doce', label: 'Riacho Doce' },
      { value: 'garça-torta', label: 'Garça Torta' },
      { value: 'guaxuma', label: 'Guaxuma' },
      { value: 'ipioca', label: 'Ipioca' },
      { value: 'jacarecica', label: 'Jacarecica' },
      { value: 'antares', label: 'Antares' },
      { value: 'serraria', label: 'Serraria' },
      { value: 'tabuleiro-dos-martins', label: 'Tabuleiro dos Martins' },
      { value: 'benedito-bentes', label: 'Benedito Bentes' },
      { value: 'clima-bom', label: 'Clima Bom' },
    ],
  },
  {
    value: 'teresina',
    label: 'Teresina',
    state: 'PI',
    population: 870_000,
    neighborhoods: [
      { value: 'joquei', label: 'Jóquei' },
      { value: 'fatima-teresina', label: 'Fátima' },
      { value: 'horto-teresina', label: 'Horto' },
      { value: 'ininga', label: 'Ininga' },
      { value: 'ilhotas', label: 'Ilhotas' },
      { value: 'centro-teresina', label: 'Centro' },
      { value: 'sao-cristovao-teresina', label: 'São Cristóvão' },
      { value: 'monte-castelo-teresina', label: 'Monte Castelo' },
      { value: 'mocambinho', label: 'Mocambinho' },
      { value: 'piçarra', label: 'Piçarra' },
      { value: 'noivos', label: 'Noivos' },
      { value: 'lourival-parente', label: 'Lourival Parente' },
      { value: 'uruguai', label: 'Uruguai' },
      { value: 'primavera-teresina', label: 'Primavera' },
      { value: 'santa-maria-codipi', label: 'Santa Maria da Codipi' },
      { value: 'dirceu-arcoverde', label: 'Dirceu Arcoverde' },
      { value: 'itarare', label: 'Itararé' },
      { value: 'angelim-teresina', label: 'Angelim' },
      { value: 'parque-brasil-teresina', label: 'Parque Brasil' },
    ],
  },
  {
    value: 'natal',
    label: 'Natal',
    state: 'RN',
    population: 890_000,
    neighborhoods: [
      { value: 'ponta-negra', label: 'Ponta Negra' },
      { value: 'petropolis-natal', label: 'Petrópolis' },
      { value: 'tirol', label: 'Tirol' },
      { value: 'cidade-alta', label: 'Cidade Alta' },
      { value: 'lagoa-nova', label: 'Lagoa Nova' },
      { value: 'candelaria', label: 'Candelária' },
      { value: 'capim-macio', label: 'Capim Macio' },
      { value: 'ribeira', label: 'Ribeira' },
      { value: 'alecrim', label: 'Alecrim' },
      { value: 'areia-preta', label: 'Areia Preta' },
      { value: 'praia-do-meio', label: 'Praia do Meio' },
      { value: 'mae-luiza', label: 'Mãe Luíza' },
      { value: 'barro-vermelho', label: 'Barro Vermelho' },
      { value: 'lagoa-seca', label: 'Lagoa Seca' },
      { value: 'nova-descoberta-natal', label: 'Nova Descoberta' },
      { value: 'cidade-da-esperança', label: 'Cidade da Esperança' },
      { value: 'dix-sept-rosado', label: 'Dix-Sept Rosado' },
      { value: 'quintas', label: 'Quintas' },
      { value: 'nordeste-natal', label: 'Nordeste' },
      { value: 'igapo', label: 'Igapó' },
      { value: 'potengi', label: 'Potengi' },
      { value: 'redinha', label: 'Redinha' },
      { value: 'neropolis', label: 'Neropólis' },
      { value: 'pitimbu', label: 'Pitimbu' },
      { value: 'planalto-natal', label: 'Planalto' },
    ],
  },
  {
    value: 'joao-pessoa',
    label: 'João Pessoa',
    state: 'PB',
    population: 820_000,
    neighborhoods: [
      { value: 'tambau', label: 'Tambaú' },
      { value: 'manaira', label: 'Manaíra' },
      { value: 'cabo-branco', label: 'Cabo Branco' },
      { value: 'bessa', label: 'Bessa' },
      { value: 'altiplano', label: 'Altiplano' },
      { value: 'jardim-oceania', label: 'Jardim Oceania' },
      { value: 'aeroclube', label: 'Aeroclube' },
      { value: 'brisamar', label: 'Brisamar' },
      { value: 'jardim-luna', label: 'Jardim Luna' },
      { value: 'tambia', label: 'Tambiá' },
      { value: 'centro-joao-pessoa', label: 'Centro' },
      { value: 'torre-jp', label: 'Torre' },
      { value: 'expedicionarios', label: 'Expedicionários' },
      { value: 'estados', label: 'Estados' },
      { value: 'miramar', label: 'Miramar' },
      { value: 'jaguaribe-jp', label: 'Jaguaribe' },
      { value: 'cristo-redentor-jp', label: 'Cristo Redentor' },
      { value: 'bancarios', label: 'Bancários' },
      { value: 'mangabeira-jp', label: 'Mangabeira' },
      { value: 'valentina', label: 'Valentina' },
      { value: 'geisel', label: 'Geisel' },
      { value: 'jose-americo', label: 'José Américo' },
      { value: 'agua-fria-jp', label: 'Água Fria' },
      { value: 'penha-jp', label: 'Penha' },
      { value: 'roger', label: 'Roger' },
    ],
  },
  {
    value: 'campo-grande',
    label: 'Campo Grande',
    state: 'MS',
    population: 920_000,
    neighborhoods: [
      { value: 'centro-campo-grande', label: 'Centro' },
      { value: 'jardim-dos-estados', label: 'Jardim dos Estados' },
      { value: 'cidade-jardim-ms', label: 'Cidade Jardim' },
      { value: 'chacara-cachoeira', label: 'Chácara Cachoeira' },
      { value: 'vilas-boas', label: 'Vilas Boas' },
      { value: 'carandá-bosque', label: 'Carandá Bosque' },
      { value: 'santa-fe', label: 'Santa Fé' },
      { value: 'nova-lima-ms', label: 'Nova Lima' },
      { value: 'tiradentes-ms', label: 'Tiradentes' },
      { value: 'taveiropolis', label: 'Taveirópolis' },
      { value: 'monte-castelo-ms', label: 'Monte Castelo' },
      { value: 'amambai', label: 'Amambaí' },
      { value: 'vila-planalto', label: 'Vila Planalto' },
      { value: 'coronel-antonino', label: 'Coronel Antonino' },
      { value: 'itanhanga-ms', label: 'Itanhangá' },
      { value: 'bela-vista-ms', label: 'Bela Vista' },
      { value: 'autonomista', label: 'Autonomista' },
      { value: 'santo-amaro-ms', label: 'Santo Amaro' },
      { value: 'sao-francisco-ms', label: 'São Francisco' },
      { value: 'seminario-ms', label: 'Seminário' },
    ],
  },
  // ============================================================================
  // TOP 21-40 - Major Cities
  // ============================================================================
  {
    value: 'sao-goncalo',
    label: 'São Gonçalo',
    state: 'RJ',
    population: 960_000,
    neighborhoods: [
      { value: 'neves', label: 'Neves' },
      { value: 'alcantara', label: 'Alcântara' },
      { value: 'centro-sao-goncalo', label: 'Centro' },
      { value: 'maria-paula', label: 'Maria Paula' },
      { value: 'trindade-sg', label: 'Trindade' },
      { value: 'paraiso-sg', label: 'Paraíso' },
      { value: 'estrela-do-norte', label: 'Estrela do Norte' },
      { value: 'rio-do-ouro', label: 'Rio do Ouro' },
      { value: 'colubande', label: 'Colubandê' },
      { value: 'jardim-catarina', label: 'Jardim Catarina' },
      { value: 'barro-vermelho-sg', label: 'Barro Vermelho' },
      { value: 'mutondo', label: 'Mutondo' },
      { value: 'ze-garoto', label: 'Zé Garoto' },
      { value: 'nova-cidade', label: 'Nova Cidade' },
      { value: 'boaçu', label: 'Boaçu' },
      { value: 'rocha-sg', label: 'Rocha' },
      { value: 'porto-velho-sg', label: 'Porto Velho' },
      { value: 'mutuá', label: 'Mutuá' },
    ],
  },
  {
    value: 'niteroi',
    label: 'Niterói',
    state: 'RJ',
    population: 515_000,
    neighborhoods: [
      { value: 'icarai', label: 'Icaraí' },
      { value: 'santa-rosa-niteroi', label: 'Santa Rosa' },
      { value: 'ingá', label: 'Ingá' },
      { value: 'centro-niteroi', label: 'Centro' },
      { value: 'charitas', label: 'Charitas' },
      { value: 'sao-francisco-niteroi', label: 'São Francisco' },
      { value: 'boa-viagem-niteroi', label: 'Boa Viagem' },
      { value: 'gragoata', label: 'Gragoatá' },
      { value: 'vital-brazil', label: 'Vital Brazil' },
      { value: 'fonseca', label: 'Fonseca' },
      { value: 'barreto', label: 'Barreto' },
      { value: 'sao-domingos', label: 'São Domingos' },
      { value: 'jurujuba', label: 'Jurujuba' },
      { value: 'piratininga-niteroi', label: 'Piratininga' },
      { value: 'camboinhas', label: 'Camboinhas' },
      { value: 'itaipu', label: 'Itaipu' },
      { value: 'itacoatiara', label: 'Itacoatiara' },
      { value: 'largo-da-batalha', label: 'Largo da Batalha' },
      { value: 'pendotiba', label: 'Pendotiba' },
      { value: 'engenho-do-mato', label: 'Engenho do Mato' },
      { value: 'cafuba', label: 'Cafubá' },
      { value: 'maravista', label: 'Maravista' },
      { value: 'santo-antônio-niteroi', label: 'Santo Antônio' },
      { value: 'cubango', label: 'Cubango' },
    ],
  },
  {
    value: 'cuiaba',
    label: 'Cuiabá',
    state: 'MT',
    population: 620_000,
    neighborhoods: [
      { value: 'centro-cuiaba', label: 'Centro' },
      { value: 'goiabeiras-cuiaba', label: 'Goiabeiras' },
      { value: 'jardim-das-americas-cuiaba', label: 'Jardim das Américas' },
      { value: 'quilombo', label: 'Quilombo' },
      { value: 'cpa-i', label: 'CPA I' },
      { value: 'cpa-ii', label: 'CPA II' },
      { value: 'cpa-iii', label: 'CPA III' },
      { value: 'cpa-iv', label: 'CPA IV' },
      { value: 'porto', label: 'Porto' },
      { value: 'araes', label: 'Araés' },
      { value: 'popular', label: 'Popular' },
      { value: 'bandeirantes-cuiaba', label: 'Bandeirantes' },
      { value: 'alvorada-cuiaba', label: 'Alvorada' },
      { value: 'dom-aquino', label: 'Dom Aquino' },
      { value: 'cidade-verde', label: 'Cidade Verde' },
      { value: 'bosque-da-saude-cuiaba', label: 'Bosque da Saúde' },
      { value: 'jardim-california', label: 'Jardim Califórnia' },
      { value: 'santa-rosa-cuiaba', label: 'Santa Rosa' },
      { value: 'duque-de-caxias-cuiaba', label: 'Duque de Caxias' },
      { value: 'coophema', label: 'Coophema' },
    ],
  },
  {
    value: 'aracaju',
    label: 'Aracaju',
    state: 'SE',
    population: 665_000,
    neighborhoods: [
      { value: '13-de-julho', label: '13 de Julho' },
      { value: 'jardins-aracaju', label: 'Jardins' },
      { value: 'grageru', label: 'Grageru' },
      { value: 'atalaia', label: 'Atalaia' },
      { value: 'luzia', label: 'Luzia' },
      { value: 'salgado-filho', label: 'Salgado Filho' },
      { value: 'suissa', label: 'Suíssa' },
      { value: 'centro-aracaju', label: 'Centro' },
      { value: 'sao-jose-aracaju', label: 'São José' },
      { value: 'farolandia', label: 'Farolândia' },
      { value: 'coroa-do-meio', label: 'Coroa do Meio' },
      { value: 'ponto-novo', label: 'Ponto Novo' },
      { value: 'inacio-barbosa', label: 'Inácio Barbosa' },
      { value: 'jabotiana', label: 'Jabotiana' },
      { value: 'aruana', label: 'Aruana' },
      { value: 'mosqueiro', label: 'Mosqueiro' },
      { value: 'santo-antonio-aracaju', label: 'Santo Antônio' },
      { value: 'getulio-vargas', label: 'Getúlio Vargas' },
      { value: 'siqueira-campos', label: 'Siqueira Campos' },
      { value: 'pereira-lobo', label: 'Pereira Lobo' },
    ],
  },
  {
    value: 'vitoria',
    label: 'Vitória',
    state: 'ES',
    population: 365_000,
    neighborhoods: [
      { value: 'praia-do-canto', label: 'Praia do Canto' },
      { value: 'jardim-camburi', label: 'Jardim Camburi' },
      { value: 'jardim-da-penha', label: 'Jardim da Penha' },
      { value: 'mata-da-praia', label: 'Mata da Praia' },
      { value: 'enseada-do-sua', label: 'Enseada do Suá' },
      { value: 'bento-ferreira', label: 'Bento Ferreira' },
      { value: 'centro-vitoria', label: 'Centro' },
      { value: 'santa-lucia-es', label: 'Santa Lúcia' },
      { value: 'barro-vermelho-vitoria', label: 'Barro Vermelho' },
      { value: 'praia-do-sua', label: 'Praia do Suá' },
      { value: 'santa-helena', label: 'Santa Helena' },
      { value: 'goiabeiras-vitoria', label: 'Goiabeiras' },
      { value: 'republica-vitoria', label: 'República' },
      { value: 'ilha-do-principe', label: 'Ilha do Príncipe' },
      { value: 'ilha-santa-maria', label: 'Ilha de Santa Maria' },
      { value: 'consolacao-es', label: 'Consolação' },
      { value: 'forte-sao-joao', label: 'Forte São João' },
      { value: 'horto-vitoria', label: 'Horto' },
      { value: 'maruipe', label: 'Maruípe' },
      { value: 'jucutuquara', label: 'Jucutuquara' },
    ],
  },
  {
    value: 'florianopolis',
    label: 'Florianópolis',
    state: 'SC',
    population: 510_000,
    neighborhoods: [
      { value: 'centro-floripa', label: 'Centro' },
      { value: 'lagoa-da-conceicao', label: 'Lagoa da Conceição' },
      { value: 'jurere', label: 'Jurerê' },
      { value: 'canasvieiras', label: 'Canasvieiras' },
      { value: 'ingleses', label: 'Ingleses' },
      { value: 'campeche', label: 'Campeche' },
      { value: 'trindade', label: 'Trindade' },
      { value: 'itacorubi', label: 'Itacorubi' },
      { value: 'coqueiros', label: 'Coqueiros' },
      { value: 'agronomica', label: 'Agronômica' },
      { value: 'barra-da-lagoa', label: 'Barra da Lagoa' },
      { value: 'santo-antonio-lisboa', label: 'Santo Antônio de Lisboa' },
      { value: 'sambaqui', label: 'Sambaqui' },
      { value: 'cacupe', label: 'Cacupé' },
      { value: 'rio-tavares', label: 'Rio Tavares' },
      { value: 'ribeirao-da-ilha', label: 'Ribeirão da Ilha' },
      { value: 'pantano-do-sul', label: 'Pântano do Sul' },
      { value: 'armacao-floripa', label: 'Armação' },
      { value: 'morro-das-pedras', label: 'Morro das Pedras' },
      { value: 'carvoeira', label: 'Carvoeira' },
      { value: 'pantanal-floripa', label: 'Pantanal' },
      { value: 'corrego-grande', label: 'Córrego Grande' },
      { value: 'santa-monica-floripa', label: 'Santa Mônica' },
      { value: 'saco-grande', label: 'Saco Grande' },
      { value: 'monte-verde-floripa', label: 'Monte Verde' },
      { value: 'vargem-pequena', label: 'Vargem Pequena' },
      { value: 'vargem-grande-floripa', label: 'Vargem Grande' },
      { value: 'ratones', label: 'Ratones' },
      { value: 'daniela', label: 'Daniela' },
      { value: 'ponta-das-canas', label: 'Ponta das Canas' },
      { value: 'cachoeira-do-bom-jesus', label: 'Cachoeira do Bom Jesus' },
      { value: 'santinho', label: 'Santinho' },
      { value: 'praia-brava-floripa', label: 'Praia Brava' },
    ],
  },
  // ============================================================================
  // TOP 41-60 - Important Regional Cities
  // ============================================================================
  {
    value: 'sao-bernardo-do-campo',
    label: 'São Bernardo do Campo',
    state: 'SP',
    population: 840_000,
    neighborhoods: [
      { value: 'centro-sbc', label: 'Centro' },
      { value: 'rudge-ramos', label: 'Rudge Ramos' },
      { value: 'nova-petropolis', label: 'Nova Petrópolis' },
      { value: 'baeta-neves', label: 'Baeta Neves' },
      { value: 'jordanopolis', label: 'Jordanópolis' },
      { value: 'assuncao', label: 'Assunção' },
      { value: 'planalto-sbc', label: 'Planalto' },
      { value: 'demarchi', label: 'Demarchi' },
      { value: 'pauliceia', label: 'Paulicéia' },
      { value: 'ferrazopolis', label: 'Ferrazópolis' },
      { value: 'independencia-sbc', label: 'Independência' },
      { value: 'taboao-sbc', label: 'Taboão' },
      { value: 'cooperativa', label: 'Cooperativa' },
      { value: 'riacho-grande', label: 'Riacho Grande' },
      { value: 'dos-casa', label: 'Dos Casa' },
      { value: 'montanhao', label: 'Montanhão' },
      { value: 'alves-dias', label: 'Alves Dias' },
      { value: 'batistini', label: 'Batistini' },
    ],
  },
  {
    value: 'santo-andre',
    label: 'Santo André',
    state: 'SP',
    population: 740_000,
    neighborhoods: [
      { value: 'centro-santo-andre', label: 'Centro' },
      { value: 'jardim-santo-andre', label: 'Jardim' },
      { value: 'vila-assuncao', label: 'Vila Assunção' },
      { value: 'campestre', label: 'Campestre' },
      { value: 'bairro-jardim', label: 'Bairro Jardim' },
      { value: 'casa-branca-sa', label: 'Casa Branca' },
      { value: 'santa-teresinha', label: 'Santa Teresinha' },
      { value: 'bangu-sa', label: 'Bangu' },
      { value: 'vila-gilda', label: 'Vila Gilda' },
      { value: 'vila-bastos', label: 'Vila Bastos' },
      { value: 'vila-alpina-sa', label: 'Vila Alpina' },
      { value: 'paranapiacaba', label: 'Paranapiacaba' },
      { value: 'vila-curuça', label: 'Vila Curuçá' },
      { value: 'parque-novo-oratorio', label: 'Parque Novo Oratório' },
      { value: 'camilopolis', label: 'Camilópolis' },
      { value: 'vila-humaitá', label: 'Vila Humaitá' },
      { value: 'utinga', label: 'Utinga' },
    ],
  },
  {
    value: 'osasco',
    label: 'Osasco',
    state: 'SP',
    population: 720_000,
    neighborhoods: [
      { value: 'centro-osasco', label: 'Centro' },
      { value: 'vila-yara', label: 'Vila Yara' },
      { value: 'presidente-altino', label: 'Presidente Altino' },
      { value: 'bela-vista-osasco', label: 'Bela Vista' },
      { value: 'km-18', label: 'Km 18' },
      { value: 'piratininga-osasco', label: 'Piratininga' },
      { value: 'vila-osasco', label: 'Vila Osasco' },
      { value: 'helena-maria', label: 'Helena Maria' },
      { value: 'umuarama', label: 'Umuarama' },
      { value: 'continental', label: 'Continental' },
      { value: 'novo-osasco', label: 'Novo Osasco' },
      { value: 'quitauna', label: 'Quitaúna' },
      { value: 'pestana', label: 'Pestana' },
      { value: 'jardim-das-flores-osasco', label: 'Jardim das Flores' },
      { value: 'cidade-das-flores', label: 'Cidade das Flores' },
      { value: 'vila-campesina', label: 'Vila Campesina' },
      { value: 'jardim-dabril', label: 'Jardim D\'Abril' },
      { value: 'rochdale', label: 'Rochdale' },
    ],
  },
  {
    value: 'santos',
    label: 'Santos',
    state: 'SP',
    population: 433_000,
    neighborhoods: [
      { value: 'gonzaga', label: 'Gonzaga' },
      { value: 'boqueirao', label: 'Boqueirão' },
      { value: 'embare', label: 'Embaré' },
      { value: 'aparecida', label: 'Aparecida' },
      { value: 'pompeia-santos', label: 'Pompéia' },
      { value: 'ponta-da-praia', label: 'Ponta da Praia' },
      { value: 'centro-santos', label: 'Centro' },
      { value: 'jose-menino', label: 'José Menino' },
      { value: 'macuco', label: 'Macuco' },
      { value: 'encruzilhada', label: 'Encruzilhada' },
      { value: 'marape', label: 'Marapé' },
      { value: 'campo-grande-santos', label: 'Campo Grande' },
      { value: 'vila-mathias', label: 'Vila Mathias' },
      { value: 'vila-belmiro', label: 'Vila Belmiro' },
      { value: 'saboó', label: 'Saboó' },
      { value: 'paquetá-santos', label: 'Paquetá' },
      { value: 'valongo', label: 'Valongo' },
      { value: 'vila-nova-santos', label: 'Vila Nova' },
    ],
  },
  {
    value: 'uberlandia',
    label: 'Uberlândia',
    state: 'MG',
    population: 700_000,
    neighborhoods: [
      { value: 'centro-uberlandia', label: 'Centro' },
      { value: 'fundinho', label: 'Fundinho' },
      { value: 'santa-monica-uberlandia', label: 'Santa Mônica' },
      { value: 'saraiva', label: 'Saraiva' },
      { value: 'jardim-karaíba', label: 'Jardim Karaíba' },
      { value: 'altamira', label: 'Altamira' },
      { value: 'brasil-uberlandia', label: 'Brasil' },
      { value: 'aparecida-uberlandia', label: 'Aparecida' },
      { value: 'martins', label: 'Martins' },
      { value: 'osvaldo-rezende', label: 'Osvaldo Rezende' },
      { value: 'vigilato-pereira', label: 'Vigilato Pereira' },
      { value: 'umuarama-uberlandia', label: 'Umuarama' },
      { value: 'tibery', label: 'Tibery' },
      { value: 'santa-maria-uberlandia', label: 'Santa Maria' },
      { value: 'granada', label: 'Granada' },
      { value: 'morada-da-colina', label: 'Morada da Colina' },
      { value: 'grand-ville', label: 'Grand Ville' },
      { value: 'jardim-patrícia', label: 'Jardim Patrícia' },
    ],
  },
  {
    value: 'ribeirao-preto',
    label: 'Ribeirão Preto',
    state: 'SP',
    population: 700_000,
    neighborhoods: [
      { value: 'centro-ribeirao-preto', label: 'Centro' },
      { value: 'jardim-paulista-rp', label: 'Jardim Paulista' },
      { value: 'jardim-california-rp', label: 'Jardim Califórnia' },
      { value: 'alto-da-boa-vista-rp', label: 'Alto da Boa Vista' },
      { value: 'jardim-sumare', label: 'Jardim Sumaré' },
      { value: 'city-ribeirao', label: 'City Ribeirão' },
      { value: 'vila-seixas', label: 'Vila Seixas' },
      { value: 'jardim-america-rp', label: 'Jardim América' },
      { value: 'campos-eliseos-rp', label: 'Campos Elíseos' },
      { value: 'vila-virginia', label: 'Vila Virgínia' },
      { value: 'vila-tibirica', label: 'Vila Tibiriçá' },
      { value: 'santa-cruz-rp', label: 'Santa Cruz' },
      { value: 'ipiranga-rp', label: 'Ipiranga' },
      { value: 'jardim-nova-aliança', label: 'Jardim Nova Aliança' },
      { value: 'lagoinha-rp', label: 'Lagoinha' },
      { value: 'jardim-palma-travassos', label: 'Jardim Palma Travassos' },
      { value: 'bosque-das-juritis', label: 'Bosque das Juritis' },
    ],
  },
  {
    value: 'sorocaba',
    label: 'Sorocaba',
    state: 'SP',
    population: 690_000,
    neighborhoods: [
      { value: 'centro-sorocaba', label: 'Centro' },
      { value: 'campolim', label: 'Campolim' },
      { value: 'jardim-faculdade', label: 'Jardim Faculdade' },
      { value: 'jardim-paulistano', label: 'Jardim Paulistano' },
      { value: 'jardim-emilia', label: 'Jardim Emília' },
      { value: 'beyond-boa-vista', label: 'Beyond Boa Vista' },
      { value: 'jardim-prestes-de-barros', label: 'Jardim Prestes de Barros' },
      { value: 'vila-hortencia', label: 'Vila Hortência' },
      { value: 'vila-carvalho', label: 'Vila Carvalho' },
      { value: 'vila-independencia', label: 'Vila Independência' },
      { value: 'mangal', label: 'Mangal' },
      { value: 'alto-boa-vista-sorocaba', label: 'Alto da Boa Vista' },
      { value: 'vila-santana-sorocaba', label: 'Vila Santana' },
      { value: 'vila-barcelona', label: 'Vila Barcelona' },
      { value: 'jardim-maria-roseira', label: 'Jardim Maria do Carmo' },
      { value: 'parque-campolim', label: 'Parque Campolim' },
    ],
  },
  {
    value: 'joinville',
    label: 'Joinville',
    state: 'SC',
    population: 600_000,
    neighborhoods: [
      { value: 'centro-joinville', label: 'Centro' },
      { value: 'america-joinville', label: 'América' },
      { value: 'anita-garibaldi', label: 'Anita Garibaldi' },
      { value: 'atiradores', label: 'Atiradores' },
      { value: 'boa-vista-joinville', label: 'Boa Vista' },
      { value: 'bucarein', label: 'Bucarein' },
      { value: 'costa-e-silva', label: 'Costa e Silva' },
      { value: 'floresta-joinville', label: 'Floresta' },
      { value: 'gloria-joinville', label: 'Glória' },
      { value: 'guanabara-joinville', label: 'Guanabara' },
      { value: 'iririú', label: 'Iririú' },
      { value: 'itaum', label: 'Itaum' },
      { value: 'jardim-paraiso', label: 'Jardim Paraíso' },
      { value: 'jarivatuba', label: 'Jarivatuba' },
      { value: 'pirabeiraba', label: 'Pirabeiraba' },
      { value: 'saguaçu', label: 'Saguaçu' },
      { value: 'santo-antonio-joinville', label: 'Santo Antônio' },
      { value: 'vila-nova-joinville', label: 'Vila Nova' },
    ],
  },
  {
    value: 'contagem',
    label: 'Contagem',
    state: 'MG',
    population: 670_000,
    neighborhoods: [
      { value: 'centro-contagem', label: 'Centro' },
      { value: 'eldorado-contagem', label: 'Eldorado' },
      { value: 'ressaca', label: 'Ressaca' },
      { value: 'riacho-das-pedras', label: 'Riacho das Pedras' },
      { value: 'sede-contagem', label: 'Sede' },
      { value: 'industrial-contagem', label: 'Industrial' },
      { value: 'inconfidentes', label: 'Inconfidentes' },
      { value: 'nacional', label: 'Nacional' },
      { value: 'petropolis-contagem', label: 'Petrópolis' },
      { value: 'cinco', label: 'Cinco' },
      { value: 'agua-branca-contagem', label: 'Água Branca' },
      { value: 'novo-progresso', label: 'Novo Progresso' },
      { value: 'jardim-laguna', label: 'Jardim Laguna' },
      { value: 'cabral-contagem', label: 'Cabral' },
      { value: 'bernardo-monteiro', label: 'Bernardo Monteiro' },
    ],
  },
  // ============================================================================
  // RIO GRANDE DO NORTE - Special Focus (User Request)
  // ============================================================================
  {
    value: 'parnamirim',
    label: 'Parnamirim',
    state: 'RN',
    population: 270_000,
    neighborhoods: [
      { value: 'nova-parnamirim', label: 'Nova Parnamirim' },
      { value: 'centro-parnamirim', label: 'Centro' },
      { value: 'boa-esperanca', label: 'Boa Esperança' },
      { value: 'cohabinal', label: 'Cohabinal' },
      { value: 'rosa-dos-ventos', label: 'Rosa dos Ventos' },
      { value: 'pirangi-do-norte', label: 'Pirangi do Norte' },
      { value: 'pirangi-de-dentro', label: 'Pirangi de Dentro' },
      { value: 'pium', label: 'Pium' },
      { value: 'cotovelo', label: 'Cotovelo' },
      { value: 'emaús', label: 'Emaús' },
      { value: 'liberdade-parnamirim', label: 'Liberdade' },
      { value: 'passagem-de-areia', label: 'Passagem de Areia' },
      { value: 'parque-industrial', label: 'Parque Industrial' },
      { value: 'monte-castelo-parnamirim', label: 'Monte Castelo' },
      { value: 'cajupiranga', label: 'Cajupiranga' },
      { value: 'bela-parnamirim', label: 'Bela Parnamirim' },
    ],
  },
  {
    value: 'mossoro',
    label: 'Mossoró',
    state: 'RN',
    population: 305_000,
    neighborhoods: [
      { value: 'centro-mossoro', label: 'Centro' },
      { value: 'alto-de-sao-manoel', label: 'Alto de São Manoel' },
      { value: 'nova-betania', label: 'Nova Betânia' },
      { value: 'abolição', label: 'Abolição' },
      { value: 'aeroporto-mossoro', label: 'Aeroporto' },
      { value: 'alto-do-sumare', label: 'Alto do Sumaré' },
      { value: 'belo-horizonte-mossoro', label: 'Belo Horizonte' },
      { value: 'dom-jaime-camara', label: 'Dom Jaime Câmara' },
      { value: 'ilha-de-santa-luzia', label: 'Ilha de Santa Luzia' },
      { value: 'paredões', label: 'Paredões' },
      { value: 'presidente-costa-e-silva', label: 'Presidente Costa e Silva' },
      { value: 'santo-antonio-mossoro', label: 'Santo Antônio' },
      { value: 'alto-da-conceição', label: 'Alto da Conceição' },
      { value: 'barrocas', label: 'Barrocas' },
      { value: 'planalto-treze-de-maio', label: 'Planalto Treze de Maio' },
    ],
  },
  // ============================================================================
  // TOURIST & BEACH CITIES
  // ============================================================================
  {
    value: 'buzios',
    label: 'Búzios',
    state: 'RJ',
    population: 35_000,
    neighborhoods: [
      { value: 'centro-buzios', label: 'Centro' },
      { value: 'geriba', label: 'Geribá' },
      { value: 'ferradura', label: 'Ferradura' },
      { value: 'joao-fernandes', label: 'João Fernandes' },
      { value: 'armacao', label: 'Armação' },
      { value: 'ossos', label: 'Ossos' },
      { value: 'manguinhos', label: 'Manguinhos' },
      { value: 'tartaruga', label: 'Tartaruga' },
      { value: 'rasa', label: 'Rasa' },
      { value: 'tucuns', label: 'Tucuns' },
      { value: 'brava-buzios', label: 'Brava' },
      { value: 'forno', label: 'Forno' },
      { value: 'foca', label: 'Foca' },
      { value: 'olho-de-boi', label: 'Olho de Boi' },
      { value: 'azeda', label: 'Azeda' },
      { value: 'azedinha', label: 'Azedinha' },
    ],
  },
  {
    value: 'cabo-frio',
    label: 'Cabo Frio',
    state: 'RJ',
    population: 230_000,
    neighborhoods: [
      { value: 'centro-cabo-frio', label: 'Centro' },
      { value: 'praia-do-forte', label: 'Praia do Forte' },
      { value: 'braga', label: 'Braga' },
      { value: 'palmeiras', label: 'Palmeiras' },
      { value: 'pero', label: 'Peró' },
      { value: 'passagem', label: 'Passagem' },
      { value: 'jardim-caicara', label: 'Jardim Caiçara' },
      { value: 'portinho', label: 'Portinho' },
      { value: 'jardim-esperanca', label: 'Jardim Esperança' },
      { value: 'sao-cristovao-cabo-frio', label: 'São Cristóvão' },
      { value: 'parque-burle', label: 'Parque Burle' },
      { value: 'gamboa-cabo-frio', label: 'Gamboa' },
      { value: 'ogiva', label: 'Ogiva' },
      { value: 'porto-do-carro', label: 'Porto do Carro' },
      { value: 'monte-alegre', label: 'Monte Alegre' },
    ],
  },
  {
    value: 'arraial-do-cabo',
    label: 'Arraial do Cabo',
    state: 'RJ',
    population: 30_000,
    neighborhoods: [
      { value: 'centro-arraial', label: 'Centro' },
      { value: 'praia-dos-anjos', label: 'Praia dos Anjos' },
      { value: 'prainha', label: 'Prainha' },
      { value: 'praia-grande', label: 'Praia Grande' },
      { value: 'figueira', label: 'Figueira' },
      { value: 'cabocla', label: 'Cabocla' },
      { value: 'monte-alto', label: 'Monte Alto' },
      { value: 'novo-arraial', label: 'Novo Arraial' },
      { value: 'canal', label: 'Canal' },
      { value: 'hermes-barcelos', label: 'Hermes Barcelos' },
      { value: 'sabiá', label: 'Sabiá' },
    ],
  },
  {
    value: 'angra-dos-reis',
    label: 'Angra dos Reis',
    state: 'RJ',
    population: 215_000,
    neighborhoods: [
      { value: 'centro-angra', label: 'Centro' },
      { value: 'jacuecanga', label: 'Jacuecanga' },
      { value: 'frade', label: 'Frade' },
      { value: 'vila-velha', label: 'Vila Velha' },
      { value: 'bonfim-angra', label: 'Bonfim' },
      { value: 'praia-grande-angra', label: 'Praia Grande' },
      { value: 'japuíba', label: 'Japuíba' },
      { value: 'balneario-angra', label: 'Balneário' },
      { value: 'parque-das-palmeiras', label: 'Parque das Palmeiras' },
      { value: 'camorim', label: 'Camorim' },
      { value: 'belém-angra', label: 'Belém' },
      { value: 'bracuí', label: 'Bracuí' },
      { value: 'perequê-angra', label: 'Perequê' },
      { value: 'sapinhatuba', label: 'Sapinhatuba' },
      { value: 'caputera', label: 'Caputera' },
    ],
  },
  {
    value: 'paraty',
    label: 'Paraty',
    state: 'RJ',
    population: 45_000,
    neighborhoods: [
      { value: 'centro-historico-paraty', label: 'Centro Histórico' },
      { value: 'mangueira-paraty', label: 'Mangueira' },
      { value: 'portal-das-artes', label: 'Portal das Artes' },
      { value: 'jabaquara', label: 'Jabaquara' },
      { value: 'caborê', label: 'Caborê' },
      { value: 'pontal-paraty', label: 'Pontal' },
      { value: 'corisco', label: 'Corisco' },
      { value: 'trindade', label: 'Trindade' },
      { value: 'laranjeiras-paraty', label: 'Laranjeiras' },
      { value: 'cabore', label: 'Caborê' },
      { value: 'patrimonio', label: 'Patrimônio' },
      { value: 'chácara-paraty', label: 'Chácara' },
    ],
  },
  {
    value: 'ilheus',
    label: 'Ilhéus',
    state: 'BA',
    population: 160_000,
    neighborhoods: [
      { value: 'centro-ilheus', label: 'Centro' },
      { value: 'pontal-ilheus', label: 'Pontal' },
      { value: 'sao-sebastiao', label: 'São Sebastião' },
      { value: 'cidade-nova-ilheus', label: 'Cidade Nova' },
      { value: 'teotonio-vilela', label: 'Teotônio Vilela' },
      { value: 'hernani-sá', label: 'Hernani Sá' },
      { value: 'malhado', label: 'Malhado' },
      { value: 'conquista', label: 'Conquista' },
      { value: 'iguape', label: 'Iguape' },
      { value: 'barra-ilheus', label: 'Barra' },
      { value: 'olivença', label: 'Olivença' },
      { value: 'sul-ilheus', label: 'Sul' },
      { value: 'salobrinho', label: 'Salobrinho' },
      { value: 'castelo-novo', label: 'Castelo Novo' },
    ],
  },
  {
    value: 'porto-seguro',
    label: 'Porto Seguro',
    state: 'BA',
    population: 150_000,
    neighborhoods: [
      { value: 'centro-porto-seguro', label: 'Centro' },
      { value: 'centro-historico-ps', label: 'Centro Histórico' },
      { value: 'taperapuan', label: 'Taperapuã' },
      { value: 'mundai', label: 'Mundaí' },
      { value: 'arraial-dajuda', label: 'Arraial d\'Ajuda' },
      { value: 'trancoso', label: 'Trancoso' },
      { value: 'caraiva', label: 'Caraíva' },
      { value: 'coroa-vermelha', label: 'Coroa Vermelha' },
      { value: 'cambolo', label: 'Cambolo' },
      { value: 'mutá', label: 'Mutá' },
      { value: 'nova-cabralia', label: 'Nova Cabrália' },
      { value: 'parracho', label: 'Parracho' },
      { value: 'frei-calixto', label: 'Frei Calixto' },
      { value: 'campinho', label: 'Campinho' },
    ],
  },
  {
    value: 'maragogi',
    label: 'Maragogi',
    state: 'AL',
    population: 35_000,
    neighborhoods: [
      { value: 'centro-maragogi', label: 'Centro' },
      { value: 'praia-de-maragogi', label: 'Praia de Maragogi' },
      { value: 'antunes', label: 'Antunes' },
      { value: 'sao-bento-maragogi', label: 'São Bento' },
      { value: 'barra-grande-maragogi', label: 'Barra Grande' },
      { value: 'burgalhau', label: 'Burgalhau' },
      { value: 'peroba', label: 'Peroba' },
      { value: 'ponta-de-mangue', label: 'Ponta de Mangue' },
      { value: 'japaratinga', label: 'Japaratinga' },
      { value: 'bitingui', label: 'Bitingui' },
    ],
  },
  // ============================================================================
  // ADDITIONAL IMPORTANT CITIES
  // ============================================================================
  {
    value: 'londrina',
    label: 'Londrina',
    state: 'PR',
    population: 580_000,
    neighborhoods: [
      { value: 'centro-londrina', label: 'Centro' },
      { value: 'gleba-palhano', label: 'Gleba Palhano' },
      { value: 'jardim-petrópolis', label: 'Jardim Petrópolis' },
      { value: 'jardim-claudia', label: 'Jardim Cláudia' },
      { value: 'jardim-higienópolis', label: 'Jardim Higienópolis' },
      { value: 'jardim-vilas-boas', label: 'Jardim Vilas Boas' },
      { value: 'vila-nova-londrina', label: 'Vila Nova' },
      { value: 'aeroporto-londrina', label: 'Aeroporto' },
      { value: 'santa-rosa-londrina', label: 'Santa Rosa' },
      { value: 'shangri-la', label: 'Shangri-lá' },
      { value: 'guanabara-londrina', label: 'Guanabara' },
      { value: 'bela-suíça', label: 'Bela Suíça' },
      { value: 'quebec', label: 'Quebec' },
      { value: 'ipiranga-londrina', label: 'Ipiranga' },
      { value: 'aurora', label: 'Aurora' },
      { value: 'jamaica', label: 'Jamaica' },
    ],
  },
  {
    value: 'blumenau',
    label: 'Blumenau',
    state: 'SC',
    population: 365_000,
    neighborhoods: [
      { value: 'centro-blumenau', label: 'Centro' },
      { value: 'victor-konder', label: 'Victor Konder' },
      { value: 'velha', label: 'Velha' },
      { value: 'ponta-aguda', label: 'Ponta Aguda' },
      { value: 'vila-nova-blumenau', label: 'Vila Nova' },
      { value: 'jardim-blumenau', label: 'Jardim Blumenau' },
      { value: 'boa-vista-blumenau', label: 'Boa Vista' },
      { value: 'vila-formosa', label: 'Vila Formosa' },
      { value: 'escola-agrícola', label: 'Escola Agrícola' },
      { value: 'itoupava-norte', label: 'Itoupava Norte' },
      { value: 'itoupava-central', label: 'Itoupava Central' },
      { value: 'itoupava-seca', label: 'Itoupava Seca' },
      { value: 'badenfurt', label: 'Badenfurt' },
      { value: 'salto', label: 'Salto' },
      { value: 'garcia', label: 'Garcia' },
      { value: 'vorstadt', label: 'Vorstadt' },
    ],
  },
  {
    value: 'feira-de-santana',
    label: 'Feira de Santana',
    state: 'BA',
    population: 620_000,
    neighborhoods: [
      { value: 'centro-feira', label: 'Centro' },
      { value: 'sim', label: 'SIM' },
      { value: 'santa-monica-feira', label: 'Santa Mônica' },
      { value: 'tomba', label: 'Tomba' },
      { value: 'mangabeira-feira', label: 'Mangabeira' },
      { value: 'capuchinhos', label: 'Capuchinhos' },
      { value: 'caseb', label: 'Caseb' },
      { value: 'queimadinha', label: 'Queimadinha' },
      { value: 'brasília-feira', label: 'Brasília' },
      { value: 'sobradinho-feira', label: 'Sobradinho' },
      { value: 'ponto-central', label: 'Ponto Central' },
      { value: 'conceição', label: 'Conceição' },
      { value: 'jardim-acácia', label: 'Jardim Acácia' },
      { value: 'george-américo', label: 'George Américo' },
      { value: 'rua-nova', label: 'Rua Nova' },
      { value: 'campo-limpo-feira', label: 'Campo Limpo' },
    ],
  },
  {
    value: 'aparecida-de-goiania',
    label: 'Aparecida de Goiânia',
    state: 'GO',
    population: 600_000,
    neighborhoods: [
      { value: 'centro-aparecida', label: 'Centro' },
      { value: 'cidade-livre', label: 'Cidade Livre' },
      { value: 'setor-dos-afonsos', label: 'Setor dos Afonsos' },
      { value: 'jardim-luz', label: 'Jardim Luz' },
      { value: 'setor-garavelo', label: 'Setor Garavelo' },
      { value: 'vila-brasília', label: 'Vila Brasília' },
      { value: 'jardim-tiradentes', label: 'Jardim Tiradentes' },
      { value: 'parque-flamboyant-aparecida', label: 'Parque Flamboyant' },
      { value: 'setor-serra-dourada', label: 'Setor Serra Dourada' },
      { value: 'jardim-buriti-sereno', label: 'Jardim Buriti Sereno' },
      { value: 'papillon-park', label: 'Papillon Park' },
      { value: 'vila-garcia', label: 'Vila Garcia' },
      { value: 'jardim-riviera', label: 'Jardim Riviera' },
      { value: 'setor-aeroporto-aparecida', label: 'Setor Aeroporto' },
    ],
  },
  {
    value: 'caxias-do-sul',
    label: 'Caxias do Sul',
    state: 'RS',
    population: 520_000,
    neighborhoods: [
      { value: 'centro-caxias', label: 'Centro' },
      { value: 'exposição', label: 'Exposição' },
      { value: 'madureira', label: 'Madureira' },
      { value: 'nossa-senhora-de-lourdes', label: 'Nossa Senhora de Lourdes' },
      { value: 'panazzolo', label: 'Panazzolo' },
      { value: 'petrópolis-caxias', label: 'Petrópolis' },
      { value: 'pio-x', label: 'Pio X' },
      { value: 'rio-branco-caxias', label: 'Rio Branco' },
      { value: 'santa-catarina-caxias', label: 'Santa Catarina' },
      { value: 'são-pelegrino', label: 'São Pelegrino' },
      { value: 'universitário-caxias', label: 'Universitário' },
      { value: 'cinquentenário', label: 'Cinquentenário' },
      { value: 'charqueadas', label: 'Charqueadas' },
      { value: 'kayser', label: 'Kayser' },
      { value: 'mariani', label: 'Mariani' },
      { value: 'sagrada-família-caxias', label: 'Sagrada Família' },
    ],
  },
  {
    value: 'balneario-camboriu',
    label: 'Balneário Camboriú',
    state: 'SC',
    population: 145_000,
    neighborhoods: [
      { value: 'centro-bc', label: 'Centro' },
      { value: 'barra-sul', label: 'Barra Sul' },
      { value: 'barra-norte', label: 'Barra Norte' },
      { value: 'pioneiros', label: 'Pioneiros' },
      { value: 'nações', label: 'Nações' },
      { value: 'vila-real', label: 'Vila Real' },
      { value: 'praia-dos-amores', label: 'Praia dos Amores' },
      { value: 'ariribá', label: 'Ariribá' },
      { value: 'tabuleiro', label: 'Tabuleiro' },
      { value: 'nova-esperança-bc', label: 'Nova Esperança' },
      { value: 'estados-bc', label: 'Estados' },
      { value: 'das-nações', label: 'Das Nações' },
      { value: 'praia-brava', label: 'Praia Brava' },
      { value: 'estaleiro', label: 'Estaleiro' },
      { value: 'estaleirinho', label: 'Estaleirinho' },
      { value: 'laranjeiras-bc', label: 'Laranjeiras' },
    ],
  },
  {
    value: 'praia-grande',
    label: 'Praia Grande',
    state: 'SP',
    population: 330_000,
    neighborhoods: [
      { value: 'centro-praia-grande', label: 'Centro' },
      { value: 'boqueirao-pg', label: 'Boqueirão' },
      { value: 'canto-do-forte', label: 'Canto do Forte' },
      { value: 'guilhermina', label: 'Guilhermina' },
      { value: 'aviação', label: 'Aviação' },
      { value: 'tupi', label: 'Tupi' },
      { value: 'mirim', label: 'Mirim' },
      { value: 'ocian', label: 'Ocian' },
      { value: 'aviação', label: 'Aviação' },
      { value: 'anhanguera-pg', label: 'Anhanguera' },
      { value: 'real', label: 'Real' },
      { value: 'vila-sonia-pg', label: 'Vila Sônia' },
      { value: 'ribeirópolis', label: 'Ribeirópolis' },
      { value: 'jardim-trevo', label: 'Jardim Trevo' },
      { value: 'melvi', label: 'Melvi' },
      { value: 'florida-pg', label: 'Flórida' },
    ],
  },
  {
    value: 'guaruja',
    label: 'Guarujá',
    state: 'SP',
    population: 320_000,
    neighborhoods: [
      { value: 'pitangueiras', label: 'Pitangueiras' },
      { value: 'astúrias', label: 'Astúrias' },
      { value: 'enseada', label: 'Enseada' },
      { value: 'praia-da-enseada', label: 'Praia da Enseada' },
      { value: 'tombo', label: 'Tombo' },
      { value: 'guaiúba', label: 'Guaiúba' },
      { value: 'praia-do-perequê', label: 'Praia do Perequê' },
      { value: 'centro-guaruja', label: 'Centro' },
      { value: 'santa-rosa-guaruja', label: 'Santa Rosa' },
      { value: 'jardim-virginia-guaruja', label: 'Jardim Virgínia' },
      { value: 'jardim-cunhambebe', label: 'Jardim Cunhambebe' },
      { value: 'morrinhos', label: 'Morrinhos' },
      { value: 'jardim-las-palmas', label: 'Jardim Las Palmas' },
      { value: 'vila-alice', label: 'Vila Alice' },
      { value: 'vicente-de-carvalho', label: 'Vicente de Carvalho' },
    ],
  },
] as const

/**
 * City value type for type-safe filtering
 */
export type CityValue = (typeof BRAZILIAN_CITIES)[number]['value']

/**
 * Quick lookup map for city by value
 */
export const CITY_MAP: ReadonlyMap<string, City> = new Map(
  BRAZILIAN_CITIES.map((c) => [c.value, c])
)

/**
 * Get city display label with state abbreviation
 *
 * @param value - City slug/value
 * @returns Formatted city label (e.g., "São Paulo, SP")
 */
export function getCityLabel(value: string): string {
  const city = CITY_MAP.get(value)
  return city ? `${city.label}, ${city.state}` : value
}

/**
 * Format city for search/filter display
 *
 * @param city - City object
 * @returns Formatted string (e.g., "São Paulo, SP")
 */
export function formatCityOption(city: City): string {
  return `${city.label}, ${city.state}`
}

/**
 * Find city by value
 *
 * @param value - City slug/value
 * @returns City object or undefined
 */
export function findCity(value: string): City | undefined {
  return CITY_MAP.get(value)
}

/**
 * Check if a value is a valid city
 *
 * @param value - City slug/value to check
 * @returns true if valid city
 */
export function isValidCity(value: string): value is CityValue {
  return CITY_MAP.has(value)
}

/**
 * Get cities by state
 *
 * @param state - State abbreviation (e.g., "SP", "RJ")
 * @returns Array of cities in that state
 */
export function getCitiesByState(state: string): City[] {
  return BRAZILIAN_CITIES.filter((c) => c.state === state.toUpperCase())
}

/**
 * Get all unique states from cities list
 *
 * @returns Array of state abbreviations
 */
export function getUniqueStates(): string[] {
  return [...new Set(BRAZILIAN_CITIES.map((c) => c.state))].sort()
}

/**
 * Get neighborhoods for a specific city
 *
 * @param cityValue - City slug/value
 * @returns Array of neighborhoods or empty array if city not found
 */
export function getNeighborhoodsByCity(cityValue: string): Neighborhood[] {
  const city = CITY_MAP.get(cityValue)
  return city ? [...city.neighborhoods] : []
}

/**
 * Check if a neighborhood is valid for a given city
 *
 * @param cityValue - City slug/value
 * @param neighborhoodValue - Neighborhood slug/value
 * @returns true if the neighborhood exists in the city
 */
export function isValidNeighborhood(cityValue: string, neighborhoodValue: string): boolean {
  const city = CITY_MAP.get(cityValue)
  if (!city) return false
  return city.neighborhoods.some((n) => n.value === neighborhoodValue)
}

/**
 * Find a neighborhood by city and neighborhood value
 *
 * @param cityValue - City slug/value
 * @param neighborhoodValue - Neighborhood slug/value
 * @returns Neighborhood object or undefined
 */
export function findNeighborhood(cityValue: string, neighborhoodValue: string): Neighborhood | undefined {
  const city = CITY_MAP.get(cityValue)
  if (!city) return undefined
  return city.neighborhoods.find((n) => n.value === neighborhoodValue)
}

/**
 * Get neighborhood display label
 *
 * @param cityValue - City slug/value
 * @param neighborhoodValue - Neighborhood slug/value
 * @returns Neighborhood label or the value if not found
 */
export function getNeighborhoodLabel(cityValue: string, neighborhoodValue: string): string {
  const neighborhood = findNeighborhood(cityValue, neighborhoodValue)
  return neighborhood ? neighborhood.label : neighborhoodValue
}

/**
 * Format neighborhood for display with city context
 *
 * @param cityValue - City slug/value
 * @param neighborhoodValue - Neighborhood slug/value
 * @returns Formatted string (e.g., "Pinheiros, São Paulo")
 */
export function formatNeighborhoodOption(cityValue: string, neighborhoodValue: string): string {
  const city = CITY_MAP.get(cityValue)
  const neighborhood = findNeighborhood(cityValue, neighborhoodValue)
  if (!city || !neighborhood) return neighborhoodValue
  return `${neighborhood.label}, ${city.label}`
}
